// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  示范命令:返回应用版本号(验证 specta 强类型 IPC 管道与错误通道)。 */
	appVersion: () => typedError<string, CmdError>(__TAURI_INVOKE("app_version")),
	/**
	 *  确保引擎槽位就绪(幂等;冷路径含安装校验+rcd spawn+探活);slot_id 缺省
	 *  = default 槽位;成功后句柄快照入壳状态并返回。
	 */
	engineEnsure: (slotId: string | null) => typedError<EngineSnapshot, CmdError>(__TAURI_INVOKE("engine_ensure", { slotId })),
	/**  引擎状态快照(ensure 时刻观测值,零引擎触达;未拉起 → null)。 */
	engineStatus: () => typedError<{
	slot_id: string,
	state: EngineState,
	pid: number | null,
	socket_path: string,
} | null, CmdError>(__TAURI_INVOKE("engine_status")),
	/**
	 *  优雅退出引擎槽位(slot_id 缺省 = default;成功后清除壳内句柄;
	 *  id 不匹配/无活动槽位 = Fatal,句柄不动)。
	 */
	engineShutdown: (slotId: string | null) => typedError<null, CmdError>(__TAURI_INVOKE("engine_shutdown", { slotId })),
	/**  拉取全部 provider 连接表单 schema(经 rc 白名单 `config/providers`)。 */
	providersFetch: () => typedError<ProviderFormOut[], CmdError>(__TAURI_INVOKE("providers_fetch")),
	/**
	 *  123 云盘(官方 WebDAV)接入:表单值构造 remote 并经 `config/create` 注入
	 *  (端点用户粘贴零硬编码;密码经 rclone obscure 落加密 config)。
	 */
	connectionCreate123: (name: string, endpoint: string, account: string, appPassword: string) => typedError<null, CmdError>(__TAURI_INVOKE("connection_create_123", { name, endpoint, account, appPassword })),
	/**
	 *  浏览数据源:rc 白名单 `operations/list` 单目录列举(fs = "remote:path");
	 *  载荷 JSON 文本原样透传(壳零字段裁剪、零 schema 发明;理由见 dto.rs)。
	 */
	operationsList: (fs: string) => typedError<string, CmdError>(__TAURI_INVOKE("operations_list", { fs })),
	/**
	 *  预算决策查询(core 预算器 acquire,供前端提交前预估等待;cost 取 u32——
	 *  specta-typescript 禁导 64 位整型,调用点无损加宽至 core 的 u64)。
	 */
	budgetAcquire: (node: string, cost: number) => typedError<BudgetDecision, CmdError>(__TAURI_INVOKE("budget_acquire", { node, cost })),
	/**
	 *  提交异步 rc job(预算前置门:core `gated_submit` 先 acquire 后 submit,
	 *  Exhausted 时 job 留 queued 零引擎触达——编排层强制,前端不可绕过;
	 *  params = JSON 对象文本,壳显式解析,解析失败 Fatal 上浮)。
	 */
	jobSubmit: (node: string, method: string, kind: string, src: string, dst: string, params: string, cost: number) => typedError<GatedSubmitOut, CmdError>(__TAURI_INVOKE("job_submit", { node, method, kind, src, dst, params, cost })),
	/**  轮询单个 job(job/status 观测推进状态机;终态幂等不再触引擎)。 */
	jobPoll: (id: string) => typedError<JobPollOut, CmdError>(__TAURI_INVOKE("job_poll", { id })),
	/**  启动对账(running 且引擎侧无锚 → error 终态;返回本次对账改判清单)。 */
	jobsReconcile: () => typedError<JobRecordOut[], CmdError>(__TAURI_INVOKE("jobs_reconcile")),
};

/* Types */
/**  预算 acquire 决策(core `Decision`;`Number` 标注理由同 JobRecordOut)。 */
export type BudgetDecision = "allow" | { throttled: {
	/**  可重试时刻(epoch 毫秒)。 */
	wait_until_ms: number,
} } | "exhausted";

/**  命令错误顶层类型;经 serde 序列化为 `{ kind, msg, severity }`,由 specta 生成对应 TS 类型。 */
export type CmdError = {
	kind: ErrorKind,
	msg: string,
	severity: Severity,
};

/**
 *  引擎活动槽位快照(`EngineHandle` 观测面;`rc_client` 凭据载体不入线格式;
 *  快照口径 = ensure 时刻观测值,零引擎触达)。
 */
export type EngineSnapshot = {
	slot_id: string,
	state: EngineState,
	pid: number | null,
	socket_path: string,
};

/**  引擎进程状态(rcd.rs `RcdState` 线格式镜像)。 */
export type EngineState = "starting" | "ready" | "stopping" | "exited" | "failed";

/**
 *  错误类别。IPC 线上序列化为字符串(snake_case);新增类别须回写任务卡边界说明
 *  (M1-WP05-T01 新增 Engine/Core 已回写运行报告)。
 */
export type ErrorKind = 
/**  本地 IO(配置、缓存等读写失败)。 */
"io" | 
/**
 *  配置缺失或非法。
 * 
 *  IPC 线格式契约类别:生产代码构造点随首个配置读取命令落地。非测试构建下以
 *  `expect` 声明「尚未构造」——一旦出现构造点会因期望未失效报警,届时删除本属性
 *  (优于 allow 永久压制);测试 target 构造它以钉住线格式值,故属性限定 not(test)。
 */
"config" | 
/**  未归类内部错误(兜底;分类困难时不得用它掩盖可判定类别)。 */
"internal" | 
/**  引擎面错误(partiverse-engine:M1-WP05-T01 新增,severity 保真)。 */
"engine" | 
/**  核心面错误(partiverse-core:M1-WP05-T01 新增,severity 保真)。 */
"core";

/**  连接表单单字段描述(core `FieldDescription` 七属性直映)。 */
export type FieldDesc = {
	name: string,
	field_type: string,
	required: boolean,
	is_password: boolean,
	advanced: boolean,
	exclusive: boolean,
	/**
	 *  默认值(JSON 文本,null → 无):specta 的 `Value` Type 实现为递归内联
	 *  类型,导出期无限递归(128MB 栈实测溢出),动态 JSON 一律文本过线。
	 */
	default: string | null,
};

/**  预算门提交结果(core `GatedSubmit`;Exhausted=job 留 queued 零引擎触达)。 */
export type GatedSubmitOut = ({ submitted: JobRecordOut }) & { exhausted?: never; throttled?: never } | ({ throttled: {
	/**  可重试时刻(epoch 毫秒)。 */
	wait_until_ms: number,
} }) & { exhausted?: never; submitted?: never } | ({ exhausted: JobRecordOut }) & { submitted?: never; throttled?: never };

/**  poll 结果:记录 + done 态 output 载荷(JSON 文本,其余 null)。 */
export type JobPollOut = {
	record: JobRecordOut,
	output: string | null,
};

/**  jobs 表行(core `JobRecord` 直映;零文件内容,红线 3)。 */
export type JobRecordOut = {
	id: string,
	kind: string,
	src: string,
	dst: string,
	status: JobStatusOut,
	/**
	 *  rc jobid:specta-typescript 禁导 i64,经官方 `Number` 标注
	 *  (jobid 远小于 2^53,精度损失不可达)。
	 */
	engine_job_id: number,
	error: string | null,
	severity: Severity | null,
	created_at: string,
	updated_at: string,
};

/**  job 状态(core `JobStatus` 线格式镜像)。 */
export type JobStatusOut = "queued" | "running" | "done" | "error";

/**  单个 provider 的连接表单 schema(core `ProviderForm` 线格式)。 */
export type ProviderFormOut = {
	name: string,
	description: string,
	fields: FieldDesc[],
};

/**  错误严重度三级镜像(线值与 core `Severity` 的 Display 一致)。 */
export type Severity = 
/**  瞬态:重试可能成功。 */
"retryable" | 
/**  持久:重试无意义。 */
"fatal" | 
/**  应用层显式中断。 */
"interrupted";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

