// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  示范命令:返回应用版本号(验证 specta 强类型 IPC 管道与错误通道)。 */
	appVersion: () => typedError<string, CmdError>(__TAURI_INVOKE("app_version")),
	/**
	 *  确保引擎槽位就绪(幂等;冷路径含安装校验+rcd spawn+探活);slot_id 缺省
	 *  = default 槽位;成功后句柄快照入壳状态并返回。
	 */
	engineEnsure: (slotId: string | null) => typedError<EngineSnapshot, CmdError>(__TAURI_INVOKE("engine_ensure", { slotId })),
	/**  引擎状态快照(ensure 时刻观测值,零引擎触达;未拉起 → null)。 */
	engineStatus: () => typedError<{
	slot_id: string,
	state: EngineState,
	pid: number | null,
	socket_path: string,
} | null, CmdError>(__TAURI_INVOKE("engine_status")),
	/**
	 *  优雅退出引擎槽位(slot_id 缺省 = default;成功后清除壳内句柄;
	 *  id 不匹配/无活动槽位 = Fatal,句柄不动)。
	 */
	engineShutdown: (slotId: string | null) => typedError<null, CmdError>(__TAURI_INVOKE("engine_shutdown", { slotId })),
	/**  拉取全部 provider 连接表单 schema(经 rc 白名单 `config/providers`)。 */
	providersFetch: () => typedError<ProviderFormOut[], CmdError>(__TAURI_INVOKE("providers_fetch")),
	/**
	 *  123 云盘(官方 WebDAV)接入:表单值构造 remote 并经 `config/create` 注入
	 *  (端点用户粘贴零硬编码;密码经 rclone obscure 落加密 config)。
	 */
	connectionCreate123: (name: string, endpoint: string, account: string, appPassword: string) => typedError<null, CmdError>(__TAURI_INVOKE("connection_create_123", { name, endpoint, account, appPassword })),
	/**
	 *  百度 oob 式本地换码(M1-WP05-T08,R2 凭据钉子):code/state + client 凭据
	 *  全部由前端注入(用户侧自建应用,禁硬编码/禁日志),经 core
	 *  `BaiduOAuthFlow::exchange_code` 在本机 GET 官方 token 端点换码(code 换
	 *  token 必须本地完成,凭据零过服务器);token 经 `OAuthTokenSink` 口径交壳面
	 *  过渡件 [`InMemoryTokenSink`]——仅保留进程内存,零落盘零日志,零 token 数据
	 *  回线(返回值恒 `()`)。加密 config 最终落点沿 T02 口径延后:引擎钉定
	 *  rclone v1.75.1 无 baidu backend(实测 `config/create` 500),待 backends-go
	 *  百度后端落地后另立卡接线;沙箱提示与向导接线同期(向导守卫暂保持
	 *  channelUnavailable 上浮,Owner 裁定 2026-10-10)。
	 */
	baiduExchangeCode: (clientId: string, clientSecret: string, code: string, oauthState: string) => typedError<null, CmdError>(__TAURI_INVOKE("baidu_exchange_code", { clientId, clientSecret, code, oauthState })),
	/**
	 *  浏览数据源:rc 白名单 `operations/list` 单目录列举(fs = "remote:path");
	 *  载荷 JSON 文本原样透传(壳零字段裁剪、零 schema 发明;理由见 dto.rs)。
	 */
	operationsList: (fs: string) => typedError<string, CmdError>(__TAURI_INVOKE("operations_list", { fs })),
	/**
	 *  预算决策查询(core 预算器 acquire,供前端提交前预估等待;cost 取 u32——
	 *  specta-typescript 禁导 64 位整型,调用点无损加宽至 core 的 u64)。
	 */
	budgetAcquire: (node: string, cost: number) => typedError<BudgetDecision, CmdError>(__TAURI_INVOKE("budget_acquire", { node, cost })),
	/**
	 *  提交异步 rc job(预算前置门:core `gated_submit` 先 acquire 后 submit,
	 *  Exhausted 时 job 留 queued 零引擎触达——编排层强制,前端不可绕过;
	 *  params = JSON 对象文本,壳显式解析,解析失败 Fatal 上浮)。
	 */
	jobSubmit: (node: string, method: string, kind: string, src: string, dst: string, params: string, cost: number) => typedError<GatedSubmitOut, CmdError>(__TAURI_INVOKE("job_submit", { node, method, kind, src, dst, params, cost })),
	/**
	 *  轮询单个 job(M1-WP06-T02 升级:core `poll_with_progress`——job/status 推进
	 *  状态机 + running 带锚行顺带 core/stats 组采样落进度列;终态/停放行零引擎
	 *  触达,采样缺失不落列,采样失败结构化上浮)。
	 */
	jobPoll: (id: string) => typedError<JobPollOut, CmdError>(__TAURI_INVOKE("job_poll", { id })),
	/**  启动对账(running 且引擎侧无锚 → error 终态;返回本次对账改判清单)。 */
	jobsReconcile: () => typedError<JobRecordOut[], CmdError>(__TAURI_INVOKE("jobs_reconcile")),
	/**
	 *  新建目录(M1-WP06-T02 卡内 ③):core `fsops::fs_mkdir`(预算 acquire 前置,
	 *  rc `operations/mkdir` 双参数实测形状);Throttled/Exhausted 零引擎触达原样
	 *  上浮,由前端择时重试。
	 */
	fsMkdir: (node: string, fs: string, remote: string, cost: number) => typedError<FsOpOutcomeOut, CmdError>(__TAURI_INVOKE("fs_mkdir", { node, fs, remote, cost })),
	/**
	 *  删除目录树文件(M1-WP06-T02 卡内 ③):core `fsops::fs_delete`(rc
	 *  `operations/delete`,实测语义 = 递归删除该目录树下全部文件、保留目录壳;
	 *  指向文件 = 引擎 500 原样上浮)。前端必须预览-提交(破坏性操作禁直通)。
	 */
	fsDelete: (node: string, fs: string, cost: number) => typedError<FsOpOutcomeOut, CmdError>(__TAURI_INVOKE("fs_delete", { node, fs, cost })),
	/**
	 *  公开任务清单(M1-WP06-T02 卡内 ③):status 过滤(None = 全量),按
	 *  created_at, id 稳定序;传输队列面板单源。
	 */
	jobList: (status: "queued" | "running" | "done" | "error" | null) => typedError<JobRecordOut[], CmdError>(__TAURI_INVOKE("job_list", { status })),
	/**
	 *  取消 job(core `job_cancel`:带锚行 job/stop + 终态裁决 error/user_canceled/
	 *  Interrupted;终态行取消 = 非法迁移 Fatal)。
	 */
	jobCancel: (id: string) => typedError<JobRecordOut, CmdError>(__TAURI_INVOKE("job_cancel", { id })),
	/**
	 *  重试 job(M1-WP06-T02 卡内 ③;编排层重试退避/re-acquire 执行点):
	 *  停放行(queued 无锚,预算 Exhausted/自动回队/提交窗残留)→ 预算 re-acquire
	 *  前置,Allow 即 `revive_parked` 原地复活(同 id,清上次失败标注);error 终态
	 *  行(重试超限/Fatal/用户取消,终态零出边)→ 预算门提交**新** job(元数据由
	 *  调用方照首次提交原样供给,行内不落 params,红线 3;旧行留痕);其余状态
	 *  (running/done/带锚 queued)拒绝 Fatal,零出边。
	 */
	jobRetry: (id: string, node: string, method: string, kind: string, src: string, dst: string, params: string, cost: number) => typedError<JobRetryOut, CmdError>(__TAURI_INVOKE("job_retry", { id, node, method, kind, src, dst, params, cost })),
};

/* Types */
/**  预算 acquire 决策(core `Decision`;`Number` 标注理由同 JobRecordOut)。 */
export type BudgetDecision = "allow" | { throttled: {
	/**  可重试时刻(epoch 毫秒)。 */
	wait_until_ms: number,
} } | "exhausted";

/**  命令错误顶层类型;经 serde 序列化为 `{ kind, msg, severity }`,由 specta 生成对应 TS 类型。 */
export type CmdError = {
	kind: ErrorKind,
	msg: string,
	severity: Severity,
};

/**
 *  引擎活动槽位快照(`EngineHandle` 观测面;`rc_client` 凭据载体不入线格式;
 *  快照口径 = ensure 时刻观测值,零引擎触达)。
 */
export type EngineSnapshot = {
	slot_id: string,
	state: EngineState,
	pid: number | null,
	socket_path: string,
};

/**  引擎进程状态(rcd.rs `RcdState` 线格式镜像)。 */
export type EngineState = "starting" | "ready" | "stopping" | "exited" | "failed";

/**
 *  错误类别。IPC 线上序列化为字符串(snake_case);新增类别须回写任务卡边界说明
 *  (M1-WP05-T01 新增 Engine/Core 已回写运行报告)。
 */
export type ErrorKind = 
/**  本地 IO(配置、缓存等读写失败)。 */
"io" | 
/**
 *  配置缺失或非法。
 * 
 *  IPC 线格式契约类别:生产代码构造点随首个配置读取命令落地。非测试构建下以
 *  `expect` 声明「尚未构造」——一旦出现构造点会因期望未失效报警,届时删除本属性
 *  (优于 allow 永久压制);测试 target 构造它以钉住线格式值,故属性限定 not(test)。
 */
"config" | 
/**  未归类内部错误(兜底;分类困难时不得用它掩盖可判定类别)。 */
"internal" | 
/**  引擎面错误(partiverse-engine:M1-WP05-T01 新增,severity 保真)。 */
"engine" | 
/**  核心面错误(partiverse-core:M1-WP05-T01 新增,severity 保真)。 */
"core";

/**  连接表单单字段描述(core `FieldDescription` 七属性直映)。 */
export type FieldDesc = {
	name: string,
	field_type: string,
	required: boolean,
	is_password: boolean,
	advanced: boolean,
	exclusive: boolean,
	/**
	 *  默认值(JSON 文本,null → 无):specta 的 `Value` Type 实现为递归内联
	 *  类型,导出期无限递归(128MB 栈实测溢出),动态 JSON 一律文本过线。
	 */
	default: string | null,
};

/**  同步文件操作结果(core `fsops::FsOpOutcome` 线格式镜像;M1-WP06-T02)。 */
export type FsOpOutcomeOut = "applied" | 
/**  预算限流零引擎触达,可等待重试。 */
{ throttled: {
	/**  可重试时刻(epoch 毫秒)。 */
	wait_until_ms: number,
} } | 
/**  预算结构性拒绝(cost 超桶容)。 */
"exhausted";

/**  预算门提交结果(core `GatedSubmit`;Exhausted=job 留 queued 零引擎触达)。 */
export type GatedSubmitOut = ({ submitted: JobRecordOut }) & { exhausted?: never; throttled?: never } | ({ throttled: {
	/**  可重试时刻(epoch 毫秒)。 */
	wait_until_ms: number,
} }) & { exhausted?: never; submitted?: never } | ({ exhausted: JobRecordOut }) & { submitted?: never; throttled?: never };

/**  poll 结果:记录 + done 态 output 载荷(JSON 文本,其余 null)。 */
export type JobPollOut = {
	record: JobRecordOut,
	output: string | null,
};

/**
 *  jobs 表行(core `JobRecord` 直映;零文件内容,红线 3)。
 *  M1-WP06-T02 增补传输面四列:进度(采样来源 core/stats 组)/校验和(待
 *  哈希管线,白名单无哈希查询命令,登记非静默)/自动重试累计。
 */
export type JobRecordOut = {
	id: string,
	kind: string,
	src: string,
	dst: string,
	status: JobStatusOut,
	/**
	 *  rc jobid:specta-typescript 禁导 i64,经官方 `Option<Number>` 标注
	 *  (jobid 远小于 2^53,精度损失不可达;可空语义保留——停放行 None)。
	 */
	engine_job_id: number | null,
	error: string | null,
	severity: Severity | null,
	created_at: string,
	updated_at: string,
	/**  已传字节(core/stats 组采样;None = 未采样)。 */
	progress_bytes: number | null,
	/**  预估总字节(None = 不可比)。 */
	progress_total: number | null,
	/**  校验和标注(None = 未计算;哈希管线另卡)。 */
	checksum: string | null,
	/**  Retryable 自动回队累计。 */
	retries: number,
};

/**
 *  job 重试结果(M1-WP06-T02):Revived=停放行原地复活(同 id);Submitted=
 *  error 终态行按预算门提交**新** job(终态零出边,旧行留痕);Throttled/
 *  Exhausted = 预算门未放行(行面不变)。
 */
export type JobRetryOut = ({ revived: JobRecordOut }) & { exhausted?: never; submitted?: never; throttled?: never } | ({ submitted: JobRecordOut }) & { exhausted?: never; revived?: never; throttled?: never } | ({ throttled: {
	/**  可重试时刻(epoch 毫秒)。 */
	wait_until_ms: number,
} }) & { exhausted?: never; revived?: never; submitted?: never } | ({ exhausted: JobRecordOut }) & { revived?: never; submitted?: never; throttled?: never };

/**  job 状态(core `JobStatus` 线格式镜像;Deserialize 供命令参数面反序列化)。 */
export type JobStatusOut = "queued" | "running" | "done" | "error";

/**  单个 provider 的连接表单 schema(core `ProviderForm` 线格式)。 */
export type ProviderFormOut = {
	name: string,
	description: string,
	fields: FieldDesc[],
};

/**  错误严重度三级镜像(线值与 core `Severity` 的 Display 一致)。 */
export type Severity = 
/**  瞬态:重试可能成功。 */
"retryable" | 
/**  持久:重试无意义。 */
"fatal" | 
/**  应用层显式中断。 */
"interrupted";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

